#server:
#  port: 11000
#
#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.204:3306/yqz-fly-commerce-ware
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#logging:
#  level:
#    com.zsy: debug
