spring:
  application:
    name: mall-search
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.204:8848
        namespace: guli-mall
        group: ${spring.profiles.active}
  thymeleaf:
    cache: false
server:
  port: 12000
logging:
  level:
    com.zsy: debug
