spring:
  application:
    name: mall-auth-server
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.204:8848
        file-extension: yaml
        namespace: guli-mall
        group: ${spring.profiles.active}
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.1.214


server:
  port: 20000
